# Generated by Django 5.1.6 on 2025-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_votingevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Description',
        ),
        migrations.AddField(
            model_name='event',
            name='Price',
            field=models.CharField(default='Rs', max_length=355),
        ),
    ]
