# Generated by Django 5.1.6 on 2025-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_customer_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='event_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
