# Generated by Django 5.1.6 on 2025-03-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_artist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='event_blog',
        ),
    ]
