# Generated by Django 5.1.6 on 2025-03-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_blog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.CharField(default='', max_length=255),
        ),
    ]
